# Generated by Django 4.2.5 on 2023-11-04 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('world', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouritePlace',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('distance', models.FloatField()),
                ('xid', models.CharField()),
                ('rate', models.FloatField()),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
